### ISSUE TITLE
Switch from Math.random() to crypto.randomInt()

### ISSUE THREAD

**Issue by N-F9** [N-F9/quack.js#1]
**Is your feature request related to a problem? Please describe.**
The output of Math.random() is not cryptographically secure. The node module crypto provides a cryptographically secure random function.

**Describe the solution you'd like**
Simply switch Math.random() calls with [crypto.randomInt()](https://nodejs.org/api/crypto.html#cryptorandomintmin-max-callback) or an equivalent function.

**Additional context**
The utilities that use the Math.random() function include [Random](https://github.com/N-F9/quack.js/blob/master/src/modules/utils.ts#L65) and [GenerateID](https://github.com/N-F9/quack.js/blob/master/src/modules/utils.ts#L76)

**Comment by xjarlie** [comment]
I can do this if it's still needed?

**Comment by N-F9** [comment]
@xjarlie yes, sorry for the super late response time
